-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 13:11:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `LOGIN` VARCHAR(16) NOT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`CONTATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`CONTATO` (
  `IDCONTATO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL,
  `CEP` INT NOT NULL,
  `NROCASA` INT NULL,
  `TELEFONE` VARCHAR(20) NULL,
  `CELULAR` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`IDCONTATO`),
  INDEX `fk_CONTATO_USUARIO_idx` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_CONTATO_USUARIO`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `agenda`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
